import Anthropic from "@anthropic-ai/sdk";
import { loadPrompt } from "braintrust";
import { NextResponse } from "next/server";

const FALLBACK_SYSTEM_PROMPT = `You are a compliance reviewer for EU AI Act Article 50 transparency obligations.

You receive the full text of a financial recommendation that will be shown to a business user. Your job is to review whether the text meets Article 50 requirements for AI-generated content.

Evaluate these 4 requirements:

1. AI DISCLOSURE: The user must know this recommendation was generated by an automated system, not a human advisor. Look for explicit AI/automated system disclosure. A small label buried at the bottom is weaker than a prominent header.

2. DATA BASIS: The user must understand what specific data was used and how the system arrived at this recommendation. "We analyzed payment history" is vague. "11 of 12 invoices paid on time, averaging 28 days" is specific. Check that the actual data points are surfaced, not just referenced.

3. HUMAN AUTHORITY: The user must understand the final decision is theirs. The system recommends; it does not decide. Watch for language that implies certainty or guarantee — "this is safe" vs "we think this is a strong candidate." Also check that action buttons give the user a clear choice (approve vs. decline), not just a confirmation.

4. COMPREHENSIBILITY: The explanation must be understandable to a non-technical finance professional. No jargon, no model-speak, no black-box references. A finance lead at a 20-person company should understand every word.

For each requirement, return:
- "pass": clearly met
- "warn": partially met — intent is there but language is ambiguous or could be stronger
- "fail": missing or the text actively undermines it

Return ONLY valid JSON matching this schema:
{
  "overall": "pass" | "warn" | "fail",
  "requirements": [
    {
      "id": "ai_disclosure",
      "label": "AI Disclosure",
      "status": "pass" | "warn" | "fail",
      "finding": "specific quote or observation from the text",
      "suggestion": "how to improve (null if pass)"
    },
    {
      "id": "data_basis",
      "label": "Data Basis",
      "status": "pass" | "warn" | "fail",
      "finding": "...",
      "suggestion": "..."
    },
    {
      "id": "human_authority",
      "label": "Human Authority",
      "status": "pass" | "warn" | "fail",
      "finding": "...",
      "suggestion": "..."
    },
    {
      "id": "comprehensibility",
      "label": "Comprehensibility",
      "status": "pass" | "warn" | "fail",
      "finding": "...",
      "suggestion": "..."
    }
  ],
  "summary": "One-sentence overall assessment"
}`;

async function getSystemPrompt(): Promise<string> {
  try {
    const prompt = await loadPrompt({
      projectName: "Bridge",
      slug: "compliance-agent-prompt-4e0b",
    });
    const promptData = prompt.prompt as { messages?: Array<{ content: string; role: string }> } | undefined;
    if (promptData?.messages?.[0]?.content) {
      return promptData.messages[0].content;
    }
    return FALLBACK_SYSTEM_PROMPT;
  } catch {
    return FALLBACK_SYSTEM_PROMPT;
  }
}

const client = new Anthropic();

export async function POST(request: Request) {
  const { recommendationText } = await request.json();

  if (!recommendationText) {
    return NextResponse.json({ error: "No recommendation text provided" }, { status: 400 });
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json({ error: "ANTHROPIC_API_KEY not set" }, { status: 500 });
  }

  const systemPrompt = await getSystemPrompt();

  const message = await client.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1500,
    system: systemPrompt,
    messages: [
      {
        role: "user",
        content: `Review this recommendation text for EU AI Act Article 50 compliance:\n\n---\n${recommendationText}\n---`,
      },
    ],
  });

  const responseText = message.content[0].type === "text" ? message.content[0].text : "";

  try {
    let jsonStr = responseText;
    if (jsonStr.includes("```json")) {
      jsonStr = jsonStr.split("```json")[1].split("```")[0];
    } else if (jsonStr.includes("```")) {
      jsonStr = jsonStr.split("```")[1].split("```")[0];
    }
    const result = JSON.parse(jsonStr.trim());
    return NextResponse.json(result);
  } catch {
    return NextResponse.json({ error: "Failed to parse compliance response", raw: responseText }, { status: 500 });
  }
}
